#cloud-config

package_upgrade: true
packages:
  - realmd
  - oddjob
  - oddjob-mkhomedir
  - sssd
  - sssd-tools
  - adcli
  - krb5-workstation
  - tcpdump
  - nmap
#  - samba-common-tools


manage_resolv_conf: true
resolv_conf:
  domain: contoso.com
  options: {rotate: true, timeout: 1}
  searchdomains: [ contoso.com ]
  nameservers: [ 10.0.1.4 ]

power_state:
  mode: reboot

write_files:
#  - path: /etc/dhcp/dhclient.conf
#    append: true
#    content: | 
#       append domain-search "contoso.com";

  - path: /etc/hosts
    append: true
    content: | 
      ${CONTROLLER_IP} controller.contoso.com controller 
