#cloud-config

package_upgrade: false

write_files:
  - path: /etc/NetworkManager/conf.d/99-azure-unmanaged_with_mana.conf
    defer: true
    permissions: 0600
    content: |
      # Ignore SR-IOV interface on Azure, since it's transparently bonded
      # to the synthetic interface
      [keyfile]
      unmanaged-devices=driver:mlx4_core;driver:mlx5_core;driver:mana

runcmd:
  - dnf update -y --disablerepo='*' --enablerepo='rhui-microsoft*'
  - dnf install -y nfs-utils
  - mkdir /exports
  - chmod 755 /exports
  - echo '10.0.0.6:/exports /exports nfs nofail,vers=3,defaults 0 0' >> /etc/fstab
  - reboot

