#cloud-config

package_upgrade: true
packages:
  - realmd
  - oddjob
  - oddjob-mkhomedir
  - sssd
  - sssd-ad
  - sssd-tools
  - adcli
  - packagekit
  - tcpdump
  - nmap
  - krb5-user

#  - samba-common-tools


write_files:
  - path: /etc/netplan/99-dns.yaml
    append: false
    owner:  root:root
    permissions: '0644'
    content: |
      network:
        ethernets:
          eth0:
            nameservers:
              search: [ "contosoi.com" ]
